name: Rust

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  # DYN_MAGIC_NUMBER: ${{ secrets.DYN_MAGIC_NUMBER }} # a secret number to parse *.dyn file, defined in github
  DYN_MAGIC_NUMBER: ${{ vars.DYN_MAGIC_NUMBER }} # a secret number to parse *.dyn file, defined in github

jobs:
  build:


    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04]
        # platform: [macos-latest, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build
        # run: cargo build --release --verbose
        run: |
          cargo run
          cargo build --release

      - name: Release
        uses: softprops/action-gh-release@v1
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: v0.0.0
          name: Release Test
          body: New Release
          draft: false
          prerelease: false
          files: ./target/release/readenv
          # files: |
          #   ${{ secrets.ReleaseZipName }}.zip
          #   LICENSE 

        # with:
        #     tagName: ${{ github.ref_name }} # This only works if your workflow triggers on new tags.
        #     releaseName: 'App Name v__VERSION__' # tauri-action replaces \_\_VERSION\_\_ with the app version.
        #     releaseBody: 'See the assets to download and install this version.'
        #     releaseDraft: true
        #     prerelease: false
