name: Rust

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  DYN_NUMBER: ${{ secrets.DYN_NUMBER }} # a secret number to parse *.dyn file, defined in github

jobs:
  build:


    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04]
        # platform: [macos-latest, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build
        # run: cargo build --release --verbose
        run: cargo run

        # with:
        #     tagName: ${{ github.ref_name }} # This only works if your workflow triggers on new tags.
        #     releaseName: 'App Name v__VERSION__' # tauri-action replaces \_\_VERSION\_\_ with the app version.
        #     releaseBody: 'See the assets to download and install this version.'
        #     releaseDraft: true
        #     prerelease: false
